# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b90a339bb1cfe5bc47bcafb82a4eeab076ff91ea13597f5571fef97192613a207ae4b0b730e1ce59bc0442536889345fe470b5f84f438de0a854a0f4e1b04b87

test:
  secret_key_base: 77a49ee6dcd5a9f7e1d366a88ae8d7082b9eda82d07b0a9bfdb3cfdd8271b1de2d4ce194692f57ac3c9d2972ec2fd829119bc117ad645f46ed5f8ce048be6c1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
